services:
  auth-service:
    build: ./tutormatic-auth-service
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - auth-database
    environment:
      - SERVER_PORT=8000
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-database/tutormatic

  auth-database:
    image: postgres:18-alpine
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: ${TUTORMATIC_DATABASE}
      POSTGRES_USER: ${TUTORMATIC_USERNAME}
      POSTGRES_PASSWORD: ${TUTORMATIC_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
