spring:
  application:
    name: tutormatic-auth-service
  datasource:
    username: ${TUTORMATIC_USERNAME}
    password: ${TUTORMATIC_PASSWORD}
    url: "jdbc:postgresql://localhost:4000/tutormatic"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

security:
  jwt:
    secret: ${TUTORMATIC_JWT_SECRET}
    access-token-expiration: ${TUTORMATIC_ACCESS_TOKEN_EXPIRATION}
    refresh-token-expiration: ${TUTORMATIC_REFRESH_TOKEN_EXPIRATION}

server:
  port: 8080

