spring:
  application:
    name: tutormatic-auth-service
  datasource:
    username: ${TUTORMATIC_USERNAME}
    password: ${TUTORMATIC_PASSWORD}
    url: "jdbc:postgresql://auth-database:5432/tutormatic"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: ${TUTORMATIC_JWT_SECRET}
    access-token-expiration: ${TUTORMATIC_ACCESS_TOKEN_EXPIRATION}
    refresh-token-expiration: ${TUTORMATIC_REFRESH_TOKEN_EXPIRATION}

server:
  port: 8080

